services:
  frontend:
    image: cathalobrien/medtracker_v2_react_frontend-frontend
    container_name: medtracker-frontend
    ports:
      - "80:80"
    networks:
      - proxy-network
networks:
  proxy-network:
    external:
      name: medtracker-network